#index:
#    path: /
#    controller: App\Controller\DefaultController::index
root:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: welcome
        permanent: true
logout:
    path: /logout